### ISSUE TITLE
PWA not working

### ISSUE THREAD

**Issue by fakhrulhilal** [RobinLinus/snapdrop#226]
I installed snapdrop as PWA apps on windows 10 (via MS Edge) and iOS 14 (using safari), it doesn't work without proper connection. Suppose I've my local wifi (without internet connection), so I can use it to transfer between iOS and windows 10. It just can't load any resource (html page, js, etc).

**Comment by RobinLinus** [comment]
Should be fixed in ce8795d. Does this work for you?

**Comment by notangelmario** [comment]
checked it. it doesn't work for me

**Comment by Bellisario** [comment]
@notangelmario, the problem is that Snapdrop use the server to create rooms and to send messages to the client on some event occour. If you want to use Snapdrop in this case, you need to create a Snapdrop server in the your local network and use it with ip address (don't use localhost or you can't open your Snapdrop in other devices).

[Here](https://github.com/RobinLinus/snapdrop/blob/master/docs/local-dev.md) is all you need for a local env...

**Comment by fakhrulhilal** [comment]
@Bellisario thank you for informing. To be honest, the actual goal is running completely without internet connection. But looking at your explanation, it requires me to build my own server.
As of today, the PWA functionality still doesn't work. It just shows error page. But I'm not sure whether it's caused downloading resource file or communicating to the server for building the channel. 

My understanding, PWA allows us to run the app without connecting to server (either local or internet). So literally, it's not possible to be PWA. I think this ticket can be closed. The issue isn't relevant anymore.
